version: '3.8'

services:
  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aipage-dev
    volumes:
      # Mount source code for live development
      - ./src:/app/src
      - ./utils:/app/utils
      - ./webpack.config.js:/app/webpack.config.js
      - ./tsconfig.json:/app/tsconfig.json
      # Mount build output (so you can load it in Chrome)
      - ./build:/app/build
      # Prevent node_modules from being overwritten
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  # Production build service
  build:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: aipage-build
    volumes:
      # Mount build output
      - ./build:/app/build
    environment:
      - NODE_ENV=production
    command: npm run build
    profiles:
      - production

  # One-off build command
  build-once:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aipage-build-once
    volumes:
      - ./build:/app/build
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build
    profiles:
      - build
